project:
  type: book

book:
  title: "Repaso Fisiología"
  author: "Ariel Antinori"
  date: "15/5/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd

format:
  html:
    theme:
      - litera
      - brand
  pdf:
    documentclass: scrreprt

editor: visual