project:
  type: book

book:
  title: "Repaso Fisiología"
  author: "Ariel Antinori"
  date: 2025-05-14
  chapters:
    - index.qmd
    - 1_Renal.qmd
    - 2_Digestivo.qmd
    - 3_Fisio-del-ejercicio.qmd
    - 4_Metabolismo-energetico.qmd
    - summary.qmd

language: es

format:
  html:
    theme:
      - litera
      - brand
    toc: true
    number-sections: true
  pdf:
    documentclass: scrreprt

editor: visual
