project:
  type: book

book:
  title: "Repaso Fisiología"
  author: "Ariel Antinori"
  #date: "15/05/2025"
  chapters:
    - index.qmd
    - 1_Renal.qmd
    - summary.qmd

format:
  html:
    theme:
      - litera
      - brand
  pdf:
    documentclass: scrreprt

editor: visual