baseURL = "https://notasatomicas.github.io/"
languageCode = "es"
title = "Ingeniería del Software I"
theme = "PaperMod"

# Soporte para RSS, sitemaps, etc.
enableRobotsTXT = true

# Menús principales (puedes expandirlos)
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 1

# Parámetros del tema
[params]
  env = "production" # para eliminar el aviso "draft"
  title = "Ingeniería del Software I"
  description = "Apuntes de la materia ISI"
  author = "Notasatomicas"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowPostNavLinks = true
  defaultTheme = "light" # o "auto", "dark"
  
  homeInfoParams = { 
    Title = "Ingeniería del Software I", 
    Content = "Página donde se publican resúmenes, apuntes y temas tratados en la materia Ingeniería del Software 1. Funciona como un blog para organizar y compartir el contenido a lo largo del curso." 
  }

  mainSections = ["posts"]