baseURL = "https://notasatomicas.github.io/"
languageCode = "es"
title = "Ingeniería del Software I"
theme = "PaperMod"

# Soporte para RSS, sitemaps, etc.
enableRobotsTXT = true

# Menús principales
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 1

# Parámetros del tema
[params]
  env = "production" # para eliminar el aviso "draft"
  title = "Ingeniería del Software I"
  description = "Apuntes de la materia ISI"
  author = "Notasatomicas"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowPostNavLinks = true
  defaultTheme = "light" # o "auto", "dark"
  mainSections = ["posts"]
