name: Render and Deploy Quarto Book

on:
  push:
    branches:
      - main

jobs:
  render-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: '1.5.47'

    - name: Install XeLaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-latex-extra

    - name: Render Quarto Book
      run: quarto render .

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        publish_branch: gh-pages
