name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      # Instala TinyTeX para poder compilar PDF
      - name: Install TinyTeX
        run: |
          quarto install tinytex
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libfontconfig1

      - name: Render Book (HTML + PDF)
        run: |
          quarto render .

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
